version: '2'
services:
  web:
    build: .
    image: sources
    restart: always
    command: yarn start
    ports:
    - "3000:3000"
    depends_on:
    - database
    env_file: .env
    environment:
    - DATABASE_USER=sources
    - DATABASE_PASSWORD=sources
    - DATABASE_HOST=database
  database:
    image: postgres:latest@sha256:b8bab9bce83b2e17d94a8984a6e597d14301363dd40b6b7b2626570ddd57da79
    restart: always
    ports:
      - "5432:5432"
    environment:
    - POSTGRES_USER=sources
    - POSTGRES_PASSWORD=sources
    - POSTGRES_DB=sources
